# Generated by Django 5.0.1 on 2024-01-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_expense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='IncExpModel',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
